import { MealEntry } from "./types";
import { getMealsForDate, saveMeal } from "./storage";

// Seed data for April 1–15, 2026 (demo data for Megha's food journal)
// Covers variety: festival (Puthandu Apr 14), social occasion, approximate, restaurant, high-protein
// Daily totals targeted at 1400–1900 kcal for a 3-meal day

const SEED_DATA: { date: string; meals: MealEntry[] }[] = [
  // ── April 1 (Wednesday) ── 3 meals · ~1535 kcal
  {
    date: "2026-04-01",
    meals: [
      {
        meal_id: "seed-0401-1",
        timestamp_logged: "2026-04-01T07:45:00+05:30",
        timestamp_meal: "2026-04-01T07:45:00+05:30",
        logged_late: false,
        raw_input: "2 dosa sambar coconut chutney filter coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Dosa", quantity: "2 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 280, calories_range: [240, 330] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Coconut chutney", quantity: "1 medium bowl", confidence: 0.9, inferred: false, category: "fat", protein_level: "low", calories_estimate: 85, calories_range: [65, 110] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 485,
        meal_calories_range: [390, 600],
      },
      {
        meal_id: "seed-0401-2",
        timestamp_logged: "2026-04-01T13:00:00+05:30",
        timestamp_meal: "2026-04-01T13:00:00+05:30",
        logged_late: false,
        raw_input: "rice sambar beans poriyal curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Beans poriyal", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 80, calories_range: [60, 105] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 535,
        meal_calories_range: [425, 675],
      },
      {
        meal_id: "seed-0401-3",
        timestamp_logged: "2026-04-01T20:30:00+05:30",
        timestamp_meal: "2026-04-01T20:30:00+05:30",
        logged_late: false,
        raw_input: "2 chapati rajma curry curd",
        input_modality: "text",
        meal_type: "dinner",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Chapati", quantity: "2 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 200, calories_range: [175, 230] },
          { name: "Rajma curry", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "protein", protein_level: "high", calories_estimate: 250, calories_range: [200, 310] },
          { name: "Curd", quantity: "1 small bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 65, calories_range: [50, 85] },
        ],
        meal_calories_estimate: 515,
        meal_calories_range: [425, 625],
      },
    ],
  },

  // ── April 2 (Thursday) ── 3 meals · ~1545 kcal
  {
    date: "2026-04-02",
    meals: [
      {
        meal_id: "seed-0402-1",
        timestamp_logged: "2026-04-02T08:00:00+05:30",
        timestamp_meal: "2026-04-02T08:00:00+05:30",
        logged_late: false,
        raw_input: "3 idli sambar coconut chutney coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Idli", quantity: "3 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 210, calories_range: [185, 245] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Coconut chutney", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "fat", protein_level: "low", calories_estimate: 85, calories_range: [65, 110] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 415,
        meal_calories_range: [335, 515],
      },
      {
        meal_id: "seed-0402-2",
        timestamp_logged: "2026-04-02T12:30:00+05:30",
        timestamp_meal: "2026-04-02T12:30:00+05:30",
        logged_late: false,
        raw_input: "rice rasam potato fry curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Rasam", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 35, calories_range: [25, 50] },
          { name: "Potato fry", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 140, calories_range: [110, 175] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 560,
        meal_calories_range: [450, 700],
      },
      {
        meal_id: "seed-0402-3",
        timestamp_logged: "2026-04-02T21:00:00+05:30",
        timestamp_meal: "2026-04-02T21:00:00+05:30",
        logged_late: false,
        raw_input: "3 roti dal makhani",
        input_modality: "text",
        meal_type: "dinner",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Roti", quantity: "3 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 300, calories_range: [265, 340] },
          { name: "Dal makhani", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "protein", protein_level: "high", calories_estimate: 220, calories_range: [175, 275] },
        ],
        meal_calories_estimate: 520,
        meal_calories_range: [440, 615],
      },
    ],
  },

  // ── April 3 (Friday) ── 2 meals (no dinner — busy day) · ~985 kcal
  {
    date: "2026-04-03",
    meals: [
      {
        meal_id: "seed-0403-1",
        timestamp_logged: "2026-04-03T08:15:00+05:30",
        timestamp_meal: "2026-04-03T08:15:00+05:30",
        logged_late: false,
        raw_input: "upma and filter coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Upma", quantity: "1 large serving", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 320, calories_range: [265, 390] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 370,
        meal_calories_range: [300, 455],
      },
      {
        meal_id: "seed-0403-2",
        timestamp_logged: "2026-04-03T13:30:00+05:30",
        timestamp_meal: "2026-04-03T13:30:00+05:30",
        logged_late: false,
        raw_input: "rice sambar sundal curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Sundal", quantity: "1 medium bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "high", calories_estimate: 160, calories_range: [130, 195] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 615,
        meal_calories_range: [495, 765],
      },
    ],
  },

  // ── April 4 (Saturday) ── 3 meals (weekend, later timings) · ~1585 kcal
  {
    date: "2026-04-04",
    meals: [
      {
        meal_id: "seed-0404-1",
        timestamp_logged: "2026-04-04T09:30:00+05:30",
        timestamp_meal: "2026-04-04T09:30:00+05:30",
        logged_late: false,
        raw_input: "4 idli sambar coconut chutney",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Idli", quantity: "4 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 280, calories_range: [250, 325] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Coconut chutney", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "fat", protein_level: "low", calories_estimate: 85, calories_range: [65, 110] },
        ],
        meal_calories_estimate: 435,
        meal_calories_range: [365, 530],
      },
      {
        meal_id: "seed-0404-2",
        timestamp_logged: "2026-04-04T14:00:00+05:30",
        timestamp_meal: "2026-04-04T14:00:00+05:30",
        logged_late: false,
        raw_input: "rice mor kuzhambu poriyal curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Mor kuzhambu", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "dairy", protein_level: "low", calories_estimate: 80, calories_range: [60, 105] },
          { name: "Carrot poriyal", quantity: "1 medium bowl", confidence: 0.8, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 80, calories_range: [60, 105] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 545,
        meal_calories_range: [435, 685],
      },
      {
        meal_id: "seed-0404-3",
        timestamp_logged: "2026-04-04T20:00:00+05:30",
        timestamp_meal: "2026-04-04T20:00:00+05:30",
        logged_late: false,
        raw_input: "2 masala dosa sambar",
        input_modality: "text",
        meal_type: "dinner",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Masala dosa", quantity: "2 pieces", confidence: 0.9, inferred: false, category: "grain", protein_level: "low", calories_estimate: 550, calories_range: [465, 640] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
        ],
        meal_calories_estimate: 620,
        meal_calories_range: [515, 735],
      },
    ],
  },

  // ── April 5 (Sunday) ── 2 meals · ~940 kcal
  {
    date: "2026-04-05",
    meals: [
      {
        meal_id: "seed-0405-1",
        timestamp_logged: "2026-04-05T08:15:00+05:30",
        timestamp_meal: "2026-04-05T08:15:00+05:30",
        logged_late: false,
        raw_input: "3 idli with sambar and coconut chutney and coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Idli", quantity: "3 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 210, calories_range: [185, 245] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Coconut chutney", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "fat", protein_level: "low", calories_estimate: 85, calories_range: [65, 110] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 415,
        meal_calories_range: [335, 515],
      },
      {
        meal_id: "seed-0405-2",
        timestamp_logged: "2026-04-05T13:10:00+05:30",
        timestamp_meal: "2026-04-05T13:10:00+05:30",
        logged_late: false,
        raw_input: "lunch at home — rice with sambar poriyal and curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "approximate",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.8, inferred: true, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.85, inferred: true, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Potato poriyal", quantity: "1 medium bowl", confidence: 0.8, inferred: true, category: "vegetable", protein_level: "low", calories_estimate: 80, calories_range: [60, 105] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: true, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 535,
        meal_calories_range: [425, 675],
      },
    ],
  },

  // ── April 6 (Monday) ── 3 meals · ~1600 kcal
  {
    date: "2026-04-06",
    meals: [
      {
        meal_id: "seed-0406-1",
        timestamp_logged: "2026-04-06T07:30:00+05:30",
        timestamp_meal: "2026-04-06T07:30:00+05:30",
        logged_late: false,
        raw_input: "2 dosa with sambar and filter coffee",
        input_modality: "voice",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Dosa", quantity: "2 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 280, calories_range: [240, 330] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Coconut chutney", quantity: "1 medium bowl", confidence: 0.9, inferred: false, category: "fat", protein_level: "low", calories_estimate: 85, calories_range: [65, 110] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 485,
        meal_calories_range: [390, 600],
      },
      {
        meal_id: "seed-0406-2",
        timestamp_logged: "2026-04-06T12:45:00+05:30",
        timestamp_meal: "2026-04-06T12:45:00+05:30",
        logged_late: false,
        raw_input: "full rice meal — rice sambar kootu rasam and curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Kootu", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 90, calories_range: [70, 115] },
          { name: "Rasam", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 35, calories_range: [25, 50] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 580,
        meal_calories_range: [460, 735],
      },
      {
        meal_id: "seed-0406-3",
        timestamp_logged: "2026-04-06T20:00:00+05:30",
        timestamp_meal: "2026-04-06T20:00:00+05:30",
        logged_late: false,
        raw_input: "3 chapati with dal and curd",
        input_modality: "text",
        meal_type: "dinner",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Chapati", quantity: "3 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 300, calories_range: [265, 340] },
          { name: "Dal fry", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "protein", protein_level: "high", calories_estimate: 180, calories_range: [140, 220] },
          { name: "Curd", quantity: "1 small bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 65, calories_range: [50, 85] },
        ],
        meal_calories_estimate: 545,
        meal_calories_range: [455, 645],
      },
    ],
  },

  // ── April 7 (Tuesday) ── 2 meals (skipped dinner) · ~1020 kcal
  {
    date: "2026-04-07",
    meals: [
      {
        meal_id: "seed-0407-1",
        timestamp_logged: "2026-04-07T08:00:00+05:30",
        timestamp_meal: "2026-04-07T08:00:00+05:30",
        logged_late: false,
        raw_input: "3 idli sambar and coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Idli", quantity: "3 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 210, calories_range: [185, 245] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 330,
        meal_calories_range: [270, 405],
      },
      {
        meal_id: "seed-0407-2",
        timestamp_logged: "2026-04-07T13:15:00+05:30",
        timestamp_meal: "2026-04-07T13:15:00+05:30",
        logged_late: false,
        raw_input: "rice rasam sundal and curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Rasam", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 35, calories_range: [25, 50] },
          { name: "Sundal", quantity: "1 medium bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "high", calories_estimate: 160, calories_range: [130, 195] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 580,
        meal_calories_range: [470, 720],
      },
    ],
  },

  // ── April 8 (Wednesday) ── 3 meals + snack · ~1360 kcal
  {
    date: "2026-04-08",
    meals: [
      {
        meal_id: "seed-0408-1",
        timestamp_logged: "2026-04-08T07:45:00+05:30",
        timestamp_meal: "2026-04-08T07:45:00+05:30",
        logged_late: false,
        raw_input: "upma and coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Upma", quantity: "1 large serving", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 320, calories_range: [265, 390] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 370,
        meal_calories_range: [300, 455],
      },
      {
        meal_id: "seed-0408-2",
        timestamp_logged: "2026-04-08T12:30:00+05:30",
        timestamp_meal: "2026-04-08T12:30:00+05:30",
        logged_late: false,
        raw_input: "rice mor kuzhambu kootu",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "approximate",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.8, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Mor kuzhambu", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "dairy", protein_level: "low", calories_estimate: 80, calories_range: [60, 105] },
          { name: "Kootu", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 465,
        meal_calories_range: [375, 580],
      },
      {
        meal_id: "seed-0408-3",
        timestamp_logged: "2026-04-08T16:30:00+05:30",
        timestamp_meal: "2026-04-08T16:30:00+05:30",
        logged_late: false,
        raw_input: "murukku",
        input_modality: "text",
        meal_type: "snack",
        context: "home",
        completeness: "approximate",
        calories_confidence: "low",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Murukku", quantity: "1 large handful", confidence: 0.7, inferred: false, category: "snack", protein_level: "low", calories_estimate: 150, calories_range: [115, 190] },
        ],
        meal_calories_estimate: 150,
        meal_calories_range: [115, 190],
      },
      {
        meal_id: "seed-0408-4",
        timestamp_logged: "2026-04-08T20:30:00+05:30",
        timestamp_meal: "2026-04-08T20:30:00+05:30",
        logged_late: false,
        raw_input: "2 dosa and sambar",
        input_modality: "text",
        meal_type: "dinner",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Dosa", quantity: "2 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 280, calories_range: [240, 330] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
        ],
        meal_calories_estimate: 350,
        meal_calories_range: [290, 425],
      },
    ],
  },

  // ── April 9 (Thursday) ── 3 meals (restaurant dinner) · ~1605 kcal
  {
    date: "2026-04-09",
    meals: [
      {
        meal_id: "seed-0409-1",
        timestamp_logged: "2026-04-09T08:30:00+05:30",
        timestamp_meal: "2026-04-09T08:30:00+05:30",
        logged_late: false,
        raw_input: "3 idli sambar coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Idli", quantity: "3 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 210, calories_range: [185, 245] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 330,
        meal_calories_range: [270, 405],
      },
      {
        meal_id: "seed-0409-2",
        timestamp_logged: "2026-04-09T13:00:00+05:30",
        timestamp_meal: "2026-04-09T13:00:00+05:30",
        logged_late: false,
        raw_input: "rice meal at home",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "approximate",
        calories_confidence: "low",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.7, inferred: true, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [220, 385] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.65, inferred: true, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [45, 100] },
          { name: "Rasam", quantity: "1 medium bowl", confidence: 0.65, inferred: true, category: "vegetable", protein_level: "low", calories_estimate: 35, calories_range: [20, 55] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.65, inferred: true, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [65, 120] },
        ],
        meal_calories_estimate: 490,
        meal_calories_range: [350, 660],
      },
      {
        meal_id: "seed-0409-3",
        timestamp_logged: "2026-04-09T20:45:00+05:30",
        timestamp_meal: "2026-04-09T20:45:00+05:30",
        logged_late: false,
        raw_input: "paneer butter masala with garlic naan at restaurant",
        input_modality: "text",
        meal_type: "dinner",
        context: "restaurant",
        completeness: "complete",
        calories_confidence: "low",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Paneer butter masala", quantity: "1 medium bowl", confidence: 0.8, inferred: false, category: "protein", protein_level: "high", calories_estimate: 380, calories_range: [305, 470] },
          { name: "Garlic naan", quantity: "2 pieces", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 420, calories_range: [350, 510] },
        ],
        meal_calories_estimate: 800,
        meal_calories_range: [655, 980],
      },
    ],
  },

  // ── April 10 (Friday) ── 3 meals · ~1520 kcal
  {
    date: "2026-04-10",
    meals: [
      {
        meal_id: "seed-0410-1",
        timestamp_logged: "2026-04-10T07:15:00+05:30",
        timestamp_meal: "2026-04-10T07:15:00+05:30",
        logged_late: false,
        raw_input: "pongal sambar coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Pongal", quantity: "1 large serving", confidence: 0.9, inferred: false, category: "grain", protein_level: "medium", calories_estimate: 310, calories_range: [255, 375] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 430,
        meal_calories_range: [340, 535],
      },
      {
        meal_id: "seed-0410-2",
        timestamp_logged: "2026-04-10T13:30:00+05:30",
        timestamp_meal: "2026-04-10T13:30:00+05:30",
        logged_late: false,
        raw_input: "rice puli sadam rasam curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1 cup cooked", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 195, calories_range: [160, 240] },
          { name: "Puli sadam", quantity: "1 medium serving", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 220, calories_range: [180, 270] },
          { name: "Rasam", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "vegetable", protein_level: "low", calories_estimate: 35, calories_range: [25, 50] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 540,
        meal_calories_range: [435, 675],
      },
      {
        meal_id: "seed-0410-3",
        timestamp_logged: "2026-04-10T20:00:00+05:30",
        timestamp_meal: "2026-04-10T20:00:00+05:30",
        logged_late: false,
        raw_input: "2 chapati palak dal curd",
        input_modality: "text",
        meal_type: "dinner",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Chapati", quantity: "2 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 200, calories_range: [175, 230] },
          { name: "Palak dal", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "protein", protein_level: "high", calories_estimate: 185, calories_range: [145, 230] },
          { name: "Curd", quantity: "1 small bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 65, calories_range: [50, 85] },
        ],
        meal_calories_estimate: 450,
        meal_calories_range: [370, 545],
      },
    ],
  },

  // ── April 11 (Saturday) ── 2 meals (social brunch + late dinner) · ~1040 kcal
  {
    date: "2026-04-11",
    meals: [
      {
        meal_id: "seed-0411-1",
        timestamp_logged: "2026-04-11T11:30:00+05:30",
        timestamp_meal: "2026-04-11T11:30:00+05:30",
        logged_late: false,
        raw_input: "masala dosa and filter coffee at hotel with friends",
        input_modality: "text",
        meal_type: "lunch",
        context: "social_occasion",
        completeness: "complete",
        calories_confidence: "low",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Masala dosa", quantity: "1 large piece", confidence: 0.9, inferred: false, category: "grain", protein_level: "low", calories_estimate: 320, calories_range: [265, 390] },
          { name: "Sambar", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.9, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 440,
        meal_calories_range: [350, 550],
      },
      {
        meal_id: "seed-0411-2",
        timestamp_logged: "2026-04-11T21:45:00+05:30",
        timestamp_meal: "2026-04-11T21:45:00+05:30",
        logged_late: false,
        raw_input: "rice sambar curd — late dinner",
        input_modality: "text",
        meal_type: "dinner",
        context: "home",
        completeness: "approximate",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.8, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.85, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Curd", quantity: "1 small bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 65, calories_range: [50, 85] },
        ],
        meal_calories_estimate: 430,
        meal_calories_range: [345, 540],
      },
    ],
  },

  // ── April 12 (Sunday) ── 3 meals · ~1590 kcal
  {
    date: "2026-04-12",
    meals: [
      {
        meal_id: "seed-0412-1",
        timestamp_logged: "2026-04-12T08:30:00+05:30",
        timestamp_meal: "2026-04-12T08:30:00+05:30",
        logged_late: false,
        raw_input: "4 idli sambar coconut chutney coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Idli", quantity: "4 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 280, calories_range: [250, 325] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Coconut chutney", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "fat", protein_level: "low", calories_estimate: 85, calories_range: [65, 110] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 485,
        meal_calories_range: [400, 595],
      },
      {
        meal_id: "seed-0412-2",
        timestamp_logged: "2026-04-12T13:00:00+05:30",
        timestamp_meal: "2026-04-12T13:00:00+05:30",
        logged_late: false,
        raw_input: "rice sambar vazhaipoo kootu curd",
        input_modality: "text",
        meal_type: "lunch",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1.5 cups cooked", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 295, calories_range: [245, 360] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Vazhaipoo kootu", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "vegetable", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
        ],
        meal_calories_estimate: 545,
        meal_calories_range: [435, 685],
      },
      {
        meal_id: "seed-0412-3",
        timestamp_logged: "2026-04-12T20:15:00+05:30",
        timestamp_meal: "2026-04-12T20:15:00+05:30",
        logged_late: false,
        raw_input: "3 chapati palak paneer",
        input_modality: "text",
        meal_type: "dinner",
        context: "home",
        completeness: "complete",
        calories_confidence: "medium",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Chapati", quantity: "3 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 300, calories_range: [265, 340] },
          { name: "Palak paneer", quantity: "1 medium bowl", confidence: 0.85, inferred: false, category: "protein", protein_level: "high", calories_estimate: 280, calories_range: [225, 345] },
        ],
        meal_calories_estimate: 580,
        meal_calories_range: [490, 685],
      },
    ],
  },

  // ── April 13 (Monday) ── 1 meal + 1 snack (partial day logged) · ~435 kcal
  {
    date: "2026-04-13",
    meals: [
      {
        meal_id: "seed-0413-1",
        timestamp_logged: "2026-04-13T08:00:00+05:30",
        timestamp_meal: "2026-04-13T08:00:00+05:30",
        logged_late: false,
        raw_input: "oats and coffee quick breakfast",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "partial",
        calories_confidence: "medium",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Oats", quantity: "1 large serving", confidence: 0.85, inferred: false, category: "grain", protein_level: "medium", calories_estimate: 200, calories_range: [165, 240] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 250,
        meal_calories_range: [200, 305],
      },
      {
        meal_id: "seed-0413-2",
        timestamp_logged: "2026-04-13T16:00:00+05:30",
        timestamp_meal: "2026-04-13T16:00:00+05:30",
        logged_late: false,
        raw_input: "banana and tea",
        input_modality: "text",
        meal_type: "snack",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Banana", quantity: "1 piece", confidence: 0.95, inferred: false, category: "snack", protein_level: "low", calories_estimate: 90, calories_range: [80, 105] },
          { name: "Tea", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 35, calories_range: [25, 50] },
        ],
        meal_calories_estimate: 125,
        meal_calories_range: [105, 155],
      },
    ],
  },

  // ── April 14 (Tuesday) — PUTHANDU (Tamil New Year) ── festival context · ~1735 kcal
  {
    date: "2026-04-14",
    meals: [
      {
        meal_id: "seed-0414-1",
        timestamp_logged: "2026-04-14T09:00:00+05:30",
        timestamp_meal: "2026-04-14T09:00:00+05:30",
        logged_late: false,
        raw_input: "puthandu breakfast — idli vada sambar payasam",
        input_modality: "text",
        meal_type: "breakfast",
        context: "festival",
        completeness: "approximate",
        calories_confidence: "low",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Idli", quantity: "3 pieces", confidence: 0.85, inferred: false, category: "grain", protein_level: "low", calories_estimate: 210, calories_range: [185, 245] },
          { name: "Vada", quantity: "2 pieces", confidence: 0.85, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 290, calories_range: [240, 355] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.85, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Payasam", quantity: "1 small serving", confidence: 0.7, inferred: false, category: "dessert", protein_level: "low", calories_estimate: 150, calories_range: [115, 195] },
        ],
        meal_calories_estimate: 720,
        meal_calories_range: [590, 890],
      },
      {
        meal_id: "seed-0414-2",
        timestamp_logged: "2026-04-14T13:30:00+05:30",
        timestamp_meal: "2026-04-14T13:30:00+05:30",
        logged_late: false,
        raw_input: "puthandu thali — full festival lunch",
        input_modality: "text",
        meal_type: "lunch",
        context: "festival",
        completeness: "partial",
        calories_confidence: "low",
        quantity_certainty: "estimated",
        edited_by_user: false,
        items: [
          { name: "Rice", quantity: "1 large serving", confidence: 0.7, inferred: true, category: "grain", protein_level: "low", calories_estimate: 390, calories_range: [315, 480] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.7, inferred: true, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 100] },
          { name: "Kootu", quantity: "1 medium bowl", confidence: 0.7, inferred: true, category: "vegetable", protein_level: "low", calories_estimate: 90, calories_range: [70, 115] },
          { name: "Poriyal", quantity: "1 medium bowl", confidence: 0.7, inferred: true, category: "vegetable", protein_level: "low", calories_estimate: 80, calories_range: [60, 105] },
          { name: "Curd", quantity: "1 large bowl", confidence: 0.7, inferred: true, category: "dairy", protein_level: "medium", calories_estimate: 90, calories_range: [70, 115] },
          { name: "Payasam", quantity: "1 medium serving", confidence: 0.7, inferred: true, category: "dessert", protein_level: "low", calories_estimate: 180, calories_range: [140, 230] },
        ],
        meal_calories_estimate: 900,
        meal_calories_range: [705, 1145],
      },
    ],
  },

  // ── April 15 (Wednesday, today) ── 1 meal so far
  {
    date: "2026-04-15",
    meals: [
      {
        meal_id: "seed-0415-1",
        timestamp_logged: "2026-04-15T08:00:00+05:30",
        timestamp_meal: "2026-04-15T08:00:00+05:30",
        logged_late: false,
        raw_input: "3 idli sambar filter coffee",
        input_modality: "text",
        meal_type: "breakfast",
        context: "home",
        completeness: "complete",
        calories_confidence: "high",
        quantity_certainty: "self_reported",
        edited_by_user: false,
        items: [
          { name: "Idli", quantity: "3 pieces", confidence: 0.95, inferred: false, category: "grain", protein_level: "low", calories_estimate: 210, calories_range: [185, 245] },
          { name: "Sambar", quantity: "1 large bowl", confidence: 0.9, inferred: false, category: "protein", protein_level: "medium", calories_estimate: 70, calories_range: [50, 95] },
          { name: "Filter coffee", quantity: "1 cup", confidence: 0.95, inferred: false, category: "beverage", protein_level: "low", calories_estimate: 50, calories_range: [35, 65] },
        ],
        meal_calories_estimate: 330,
        meal_calories_range: [270, 405],
      },
    ],
  },
];

const SEED_VERSION = "v2";
const SEED_VERSION_KEY = "aara_seed_version";

export function seedMockData(): void {
  if (typeof window === "undefined") return;

  // Bump SEED_VERSION to force a re-seed with updated data
  if (localStorage.getItem(SEED_VERSION_KEY) === SEED_VERSION) return;

  // Clear any previously seeded meal data for Apr 1–15
  for (let i = 0; i <= 14; i++) {
    const d = new Date("2026-04-01T12:00:00");
    d.setDate(d.getDate() + i);
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    localStorage.removeItem(`logs:${y}-${m}-${day}`);
  }

  // Write fresh seed data
  for (const { date, meals } of SEED_DATA) {
    for (const meal of meals) {
      saveMeal(date, meal);
    }
  }

  localStorage.setItem(SEED_VERSION_KEY, SEED_VERSION);
}
